//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSystemASPX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseCases
    {
        public int EnterpriseCasesID { get; set; }
        public int EnterpriseID { get; set; }
        public string EnterpriseTitle { get; set; }
        public string EnterpriseContent { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
    }
}
