//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnterpriseSystemASPX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEnterprise
    {
        public MEnterprise()
        {
            this.MEnterpriseCases = new HashSet<MEnterpriseCases>();
        }
    
        public int MEnterpriseID { get; set; }
        public string MEnterpriseName { get; set; }
        public string MEnterpriseAddress { get; set; }
        public string MEnterpriseTelphoneNumber { get; set; }
        public string MEnterpriseBriefShort { get; set; }
        public string MEnterpriseBrief { get; set; }
        public string MEnterpriseEmail { get; set; }
        public string MEnterpriseRight { get; set; }
        public string MEnterpriseLogo { get; set; }
    
        public virtual ICollection<MEnterpriseCases> MEnterpriseCases { get; set; }
    }
}
